// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// estimate_epsilon_wrapper
Rcpp::NumericMatrix estimate_epsilon_wrapper(Rcpp::IntegerMatrix& ipat, Rcpp::IntegerMatrix& iisF, Rcpp::IntegerMatrix& iisCE, Rcpp::NumericMatrix& ieps, Rcpp::IntegerMatrix& isetD, Rcpp::IntegerMatrix& ieventD, Rcpp::NumericVector ithreshold, Rcpp::IntegerVector ithreshold1, Rcpp::IntegerVector in_p, Rcpp::NumericVector iT, Rcpp::IntegerVector iN_iter, Rcpp::NumericVector ilambdaS, Rcpp::IntegerVector ithrds, Rcpp::IntegerVector iR);
RcppExport SEXP _este_estimate_epsilon_wrapper(SEXP ipatSEXP, SEXP iisFSEXP, SEXP iisCESEXP, SEXP iepsSEXP, SEXP isetDSEXP, SEXP ieventDSEXP, SEXP ithresholdSEXP, SEXP ithreshold1SEXP, SEXP in_pSEXP, SEXP iTSEXP, SEXP iN_iterSEXP, SEXP ilambdaSSEXP, SEXP ithrdsSEXP, SEXP iRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix& >::type ipat(ipatSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix& >::type iisF(iisFSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix& >::type iisCE(iisCESEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type ieps(iepsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix& >::type isetD(isetDSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix& >::type ieventD(ieventDSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ithreshold(ithresholdSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ithreshold1(ithreshold1SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type in_p(in_pSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type iT(iTSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type iN_iter(iN_iterSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ilambdaS(ilambdaSSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ithrds(ithrdsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type iR(iRSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_epsilon_wrapper(ipat, iisF, iisCE, ieps, isetD, ieventD, ithreshold, ithreshold1, in_p, iT, iN_iter, ilambdaS, ithrds, iR));
    return rcpp_result_gen;
END_RCPP
}
// estimate_epsilon_based_on_poset_and_lambda_wrapper
Rcpp::List estimate_epsilon_based_on_poset_and_lambda_wrapper(Rcpp::IntegerMatrix& ipat, Rcpp::IntegerMatrix& iposet, Rcpp::IntegerMatrix& iisF, Rcpp::NumericMatrix& ieps, Rcpp::IntegerMatrix& isetD, Rcpp::IntegerMatrix& ieventD, Rcpp::NumericVector& ilambda, Rcpp::NumericVector ilambdaS, Rcpp::IntegerVector iL, Rcpp::CharacterVector isampling, Rcpp::IntegerVector imaxIter, Rcpp::IntegerVector iupdateStepSize, Rcpp::NumericVector itol, Rcpp::NumericVector imaxLambda, Rcpp::IntegerVector ineighborhoodDist, Rcpp::IntegerVector ithrds, Rcpp::IntegerVector iseed);
RcppExport SEXP _este_estimate_epsilon_based_on_poset_and_lambda_wrapper(SEXP ipatSEXP, SEXP iposetSEXP, SEXP iisFSEXP, SEXP iepsSEXP, SEXP isetDSEXP, SEXP ieventDSEXP, SEXP ilambdaSEXP, SEXP ilambdaSSEXP, SEXP iLSEXP, SEXP isamplingSEXP, SEXP imaxIterSEXP, SEXP iupdateStepSizeSEXP, SEXP itolSEXP, SEXP imaxLambdaSEXP, SEXP ineighborhoodDistSEXP, SEXP ithrdsSEXP, SEXP iseedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix& >::type ipat(ipatSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix& >::type iposet(iposetSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix& >::type iisF(iisFSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type ieps(iepsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix& >::type isetD(isetDSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix& >::type ieventD(ieventDSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type ilambda(ilambdaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ilambdaS(ilambdaSSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type iL(iLSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type isampling(isamplingSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type imaxIter(imaxIterSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type iupdateStepSize(iupdateStepSizeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type itol(itolSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type imaxLambda(imaxLambdaSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ineighborhoodDist(ineighborhoodDistSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ithrds(ithrdsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type iseed(iseedSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_epsilon_based_on_poset_and_lambda_wrapper(ipat, iposet, iisF, ieps, isetD, ieventD, ilambda, ilambdaS, iL, isampling, imaxIter, iupdateStepSize, itol, imaxLambda, ineighborhoodDist, ithrds, iseed));
    return rcpp_result_gen;
END_RCPP
}
// find_poset_wrapper
Rcpp::IntegerMatrix find_poset_wrapper(Rcpp::IntegerMatrix& ipat, Rcpp::IntegerVector ithrds, Rcpp::IntegerMatrix& iisF, Rcpp::IntegerMatrix& iisCE, Rcpp::NumericMatrix& ieps, Rcpp::IntegerMatrix& isetD, Rcpp::IntegerMatrix& ieventD, Rcpp::IntegerVector iFine_Tune_Num, Rcpp::NumericVector ithreshold, Rcpp::NumericVector ithreshold2, Rcpp::IntegerVector igmm_min_cluster, Rcpp::NumericVector igmm_convenience_threshold, Rcpp::NumericVector igmm_filter_threshold, Rcpp::IntegerVector in_p, Rcpp::LogicalVector iis_update_eps, Rcpp::NumericVector iT, Rcpp::IntegerVector iN_iter, Rcpp::NumericVector ilambdaS, Rcpp::IntegerVector iR);
RcppExport SEXP _este_find_poset_wrapper(SEXP ipatSEXP, SEXP ithrdsSEXP, SEXP iisFSEXP, SEXP iisCESEXP, SEXP iepsSEXP, SEXP isetDSEXP, SEXP ieventDSEXP, SEXP iFine_Tune_NumSEXP, SEXP ithresholdSEXP, SEXP ithreshold2SEXP, SEXP igmm_min_clusterSEXP, SEXP igmm_convenience_thresholdSEXP, SEXP igmm_filter_thresholdSEXP, SEXP in_pSEXP, SEXP iis_update_epsSEXP, SEXP iTSEXP, SEXP iN_iterSEXP, SEXP ilambdaSSEXP, SEXP iRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix& >::type ipat(ipatSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ithrds(ithrdsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix& >::type iisF(iisFSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix& >::type iisCE(iisCESEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type ieps(iepsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix& >::type isetD(isetDSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix& >::type ieventD(ieventDSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type iFine_Tune_Num(iFine_Tune_NumSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ithreshold(ithresholdSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ithreshold2(ithreshold2SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type igmm_min_cluster(igmm_min_clusterSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type igmm_convenience_threshold(igmm_convenience_thresholdSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type igmm_filter_threshold(igmm_filter_thresholdSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type in_p(in_pSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type iis_update_eps(iis_update_epsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type iT(iTSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type iN_iter(iN_iterSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ilambdaS(ilambdaSSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type iR(iRSEXP);
    rcpp_result_gen = Rcpp::wrap(find_poset_wrapper(ipat, ithrds, iisF, iisCE, ieps, isetD, ieventD, iFine_Tune_Num, ithreshold, ithreshold2, igmm_min_cluster, igmm_convenience_threshold, igmm_filter_threshold, in_p, iis_update_eps, iT, iN_iter, ilambdaS, iR));
    return rcpp_result_gen;
END_RCPP
}
// estimate_lambda_wrapper
Rcpp::List estimate_lambda_wrapper(Rcpp::IntegerMatrix& ipat, Rcpp::IntegerMatrix& iposet, Rcpp::IntegerMatrix& iisF, Rcpp::NumericMatrix& ieps, Rcpp::IntegerMatrix& isetD, Rcpp::IntegerMatrix& ieventD, Rcpp::NumericVector ilambdaS, Rcpp::IntegerVector iL, Rcpp::CharacterVector isampling, Rcpp::IntegerVector imaxIter, Rcpp::IntegerVector iupdateStepSize, Rcpp::NumericVector itol, Rcpp::NumericVector imaxLambda, Rcpp::IntegerVector ineighborhoodDist, Rcpp::IntegerVector ithrds, Rcpp::LogicalVector iis_update_eps, Rcpp::IntegerVector iseed);
RcppExport SEXP _este_estimate_lambda_wrapper(SEXP ipatSEXP, SEXP iposetSEXP, SEXP iisFSEXP, SEXP iepsSEXP, SEXP isetDSEXP, SEXP ieventDSEXP, SEXP ilambdaSSEXP, SEXP iLSEXP, SEXP isamplingSEXP, SEXP imaxIterSEXP, SEXP iupdateStepSizeSEXP, SEXP itolSEXP, SEXP imaxLambdaSEXP, SEXP ineighborhoodDistSEXP, SEXP ithrdsSEXP, SEXP iis_update_epsSEXP, SEXP iseedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix& >::type ipat(ipatSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix& >::type iposet(iposetSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix& >::type iisF(iisFSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type ieps(iepsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix& >::type isetD(isetDSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix& >::type ieventD(ieventDSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ilambdaS(ilambdaSSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type iL(iLSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type isampling(isamplingSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type imaxIter(imaxIterSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type iupdateStepSize(iupdateStepSizeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type itol(itolSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type imaxLambda(imaxLambdaSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ineighborhoodDist(ineighborhoodDistSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ithrds(ithrdsSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type iis_update_eps(iis_update_epsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type iseed(iseedSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_lambda_wrapper(ipat, iposet, iisF, ieps, isetD, ieventD, ilambdaS, iL, isampling, imaxIter, iupdateStepSize, itol, imaxLambda, ineighborhoodDist, ithrds, iis_update_eps, iseed));
    return rcpp_result_gen;
END_RCPP
}
// isCompatible_wrapper
Rcpp::IntegerVector isCompatible_wrapper(Rcpp::IntegerVector& igenotype, Rcpp::IntegerMatrix& iposet);
RcppExport SEXP _este_isCompatible_wrapper(SEXP igenotypeSEXP, SEXP iposetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector& >::type igenotype(igenotypeSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix& >::type iposet(iposetSEXP);
    rcpp_result_gen = Rcpp::wrap(isCompatible_wrapper(igenotype, iposet));
    return rcpp_result_gen;
END_RCPP
}
// sample_Age_T_wrapper
Rcpp::NumericMatrix sample_Age_T_wrapper(Rcpp::NumericMatrix& idata, Rcpp::NumericVector ialpha, Rcpp::NumericVector ibeta, Rcpp::NumericVector ilambda, Rcpp::IntegerVector imaxSampleIter, Rcpp::NumericVector irateE1, Rcpp::IntegerVector ithrds, Rcpp::IntegerVector iseed);
RcppExport SEXP _este_sample_Age_T_wrapper(SEXP idataSEXP, SEXP ialphaSEXP, SEXP ibetaSEXP, SEXP ilambdaSEXP, SEXP imaxSampleIterSEXP, SEXP irateE1SEXP, SEXP ithrdsSEXP, SEXP iseedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type idata(idataSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ialpha(ialphaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ibeta(ibetaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ilambda(ilambdaSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type imaxSampleIter(imaxSampleIterSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type irateE1(irateE1SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ithrds(ithrdsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type iseed(iseedSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_Age_T_wrapper(idata, ialpha, ibeta, ilambda, imaxSampleIter, irateE1, ithrds, iseed));
    return rcpp_result_gen;
END_RCPP
}
// sample_Age_TLW_wrapper
Rcpp::NumericMatrix sample_Age_TLW_wrapper(Rcpp::NumericMatrix& idata, Rcpp::NumericVector ialpha, Rcpp::NumericVector ibeta, Rcpp::NumericVector ilambda, Rcpp::IntegerVector ithrds);
RcppExport SEXP _este_sample_Age_TLW_wrapper(SEXP idataSEXP, SEXP ialphaSEXP, SEXP ibetaSEXP, SEXP ilambdaSEXP, SEXP ithrdsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type idata(idataSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ialpha(ialphaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ibeta(ibetaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ilambda(ilambdaSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ithrds(ithrdsSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_Age_TLW_wrapper(idata, ialpha, ibeta, ilambda, ithrds));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_este_estimate_epsilon_wrapper", (DL_FUNC) &_este_estimate_epsilon_wrapper, 14},
    {"_este_estimate_epsilon_based_on_poset_and_lambda_wrapper", (DL_FUNC) &_este_estimate_epsilon_based_on_poset_and_lambda_wrapper, 17},
    {"_este_find_poset_wrapper", (DL_FUNC) &_este_find_poset_wrapper, 19},
    {"_este_estimate_lambda_wrapper", (DL_FUNC) &_este_estimate_lambda_wrapper, 17},
    {"_este_isCompatible_wrapper", (DL_FUNC) &_este_isCompatible_wrapper, 2},
    {"_este_sample_Age_T_wrapper", (DL_FUNC) &_este_sample_Age_T_wrapper, 8},
    {"_este_sample_Age_TLW_wrapper", (DL_FUNC) &_este_sample_Age_TLW_wrapper, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_este(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
