# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estimate_epsilon_wrapper <- function(ipat, iisF, iisCE, ieps, isetD, ieventD, ithreshold, ithreshold1, in_p, iT, iN_iter, ilambdaS, ithrds, iR) {
    .Call('_este_estimate_epsilon_wrapper', PACKAGE = 'este', ipat, iisF, iisCE, ieps, isetD, ieventD, ithreshold, ithreshold1, in_p, iT, iN_iter, ilambdaS, ithrds, iR)
}

estimate_epsilon_based_on_poset_and_lambda_wrapper <- function(ipat, iposet, iisF, ieps, isetD, ieventD, ilambda, ilambdaS, iL, isampling, imaxIter, iupdateStepSize, itol, imaxLambda, ineighborhoodDist, ithrds, iseed) {
    .Call('_este_estimate_epsilon_based_on_poset_and_lambda_wrapper', PACKAGE = 'este', ipat, iposet, iisF, ieps, isetD, ieventD, ilambda, ilambdaS, iL, isampling, imaxIter, iupdateStepSize, itol, imaxLambda, ineighborhoodDist, ithrds, iseed)
}

find_poset_wrapper <- function(ipat, ithrds, iisF, iisCE, ieps, isetD, ieventD, iFine_Tune_Num, ithreshold, ithreshold2, igmm_min_cluster, igmm_convenience_threshold, igmm_filter_threshold, in_p, iis_update_eps, iT, iN_iter, ilambdaS, iR) {
    .Call('_este_find_poset_wrapper', PACKAGE = 'este', ipat, ithrds, iisF, iisCE, ieps, isetD, ieventD, iFine_Tune_Num, ithreshold, ithreshold2, igmm_min_cluster, igmm_convenience_threshold, igmm_filter_threshold, in_p, iis_update_eps, iT, iN_iter, ilambdaS, iR)
}

estimate_lambda_wrapper <- function(ipat, iposet, iisF, ieps, isetD, ieventD, ilambdaS, iL, isampling, imaxIter, iupdateStepSize, itol, imaxLambda, ineighborhoodDist, ithrds, iis_update_eps, iseed) {
    .Call('_este_estimate_lambda_wrapper', PACKAGE = 'este', ipat, iposet, iisF, ieps, isetD, ieventD, ilambdaS, iL, isampling, imaxIter, iupdateStepSize, itol, imaxLambda, ineighborhoodDist, ithrds, iis_update_eps, iseed)
}

isCompatible_wrapper <- function(igenotype, iposet) {
    .Call('_este_isCompatible_wrapper', PACKAGE = 'este', igenotype, iposet)
}

sample_Age_T_wrapper <- function(idata, ialpha, ibeta, ilambda, imaxSampleIter, irateE1, ithrds, iseed) {
    .Call('_este_sample_Age_T_wrapper', PACKAGE = 'este', idata, ialpha, ibeta, ilambda, imaxSampleIter, irateE1, ithrds, iseed)
}

sample_Age_TLW_wrapper <- function(idata, ialpha, ibeta, ilambda, ithrds) {
    .Call('_este_sample_Age_TLW_wrapper', PACKAGE = 'este', idata, ialpha, ibeta, ilambda, ithrds)
}

